"""Project template generator for Noode.

Creates project scaffolding based on templates.
"""

from dataclasses import dataclass, field
from enum import Enum
from pathlib import Path
from typing import Any

import structlog

logger = structlog.get_logger()


class ProjectTemplate(Enum):
    """Available project templates."""
    
    WEB_APP = "web-app"
    API = "api"
    FULLSTACK = "fullstack"
    CLI = "cli"
    LIBRARY = "library"


@dataclass
class TemplateConfig:
    """Configuration for a project template."""
    
    name: str
    description: str
    stack: list[str]
    agents: list[str]
    files: dict[str, str]  # path -> content template
    dependencies: list[str] = field(default_factory=list)


class ProjectGenerator:
    """Generate project scaffolding from templates."""
    
    TEMPLATES: dict[ProjectTemplate, TemplateConfig] = {
        ProjectTemplate.WEB_APP: TemplateConfig(
            name="Web Application",
            description="React frontend with FastAPI backend",
            stack=["React", "FastAPI", "PostgreSQL"],
            agents=["frontend", "backend", "security"],
            files={
                "frontend/src/App.tsx": '''import React from 'react';
import './App.css';

function App() {
  return (
    <div className="app">
      <header className="header">
        <h1>{{project_name}}</h1>
        <p>Built with Noode AI</p>
      </header>
      <main className="main">
        {/* Your content here */}
      </main>
    </div>
  );
}

export default App;
''',
                "frontend/src/App.css": ''':root {
  --color-primary: #6366f1;
  --color-bg: #0f172a;
  --color-text: #f8fafc;
}

.app {
  min-height: 100vh;
  background: var(--color-bg);
  color: var(--color-text);
}

.header {
  padding: 2rem;
  text-align: center;
}

.header h1 {
  background: linear-gradient(135deg, var(--color-primary), #8b5cf6);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
}
''',
                "backend/app/main.py": '''"""{{project_name}} API."""

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{{project_name}}",
    description="Generated by Noode AI",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/")
async def root():
    return {"message": "Welcome to {{project_name}}"}


@app.get("/health")
async def health():
    return {"status": "healthy"}
''',
            },
            dependencies=["fastapi", "uvicorn", "react", "typescript"],
        ),
        
        ProjectTemplate.API: TemplateConfig(
            name="REST API",
            description="FastAPI backend with database",
            stack=["FastAPI", "SQLAlchemy", "PostgreSQL"],
            agents=["backend", "security"],
            files={
                "app/main.py": '''"""{{project_name}} API."""

from fastapi import FastAPI
from app.routes import router

app = FastAPI(
    title="{{project_name}}",
    version="0.1.0",
)

app.include_router(router)


@app.get("/health")
async def health():
    return {"status": "healthy"}
''',
                "app/routes.py": '''"""API routes."""

from fastapi import APIRouter

router = APIRouter(prefix="/api/v1")


@router.get("/items")
async def list_items():
    return {"items": []}


@router.post("/items")
async def create_item(data: dict):
    return {"id": 1, **data}
''',
                "app/models.py": '''"""Database models."""

from sqlalchemy import Column, Integer, String, DateTime
from sqlalchemy.orm import declarative_base
from datetime import datetime

Base = declarative_base()


class Item(Base):
    __tablename__ = "items"
    
    id = Column(Integer, primary_key=True)
    name = Column(String(255), nullable=False)
    created_at = Column(DateTime, default=datetime.now)
''',
            },
            dependencies=["fastapi", "uvicorn", "sqlalchemy", "asyncpg"],
        ),
        
        ProjectTemplate.FULLSTACK: TemplateConfig(
            name="Full Stack Application",
            description="Complete web application with auth",
            stack=["React", "FastAPI", "PostgreSQL", "Redis"],
            agents=["frontend", "backend", "security", "research"],
            files={
                "docker-compose.yml": '''version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db/{{project_name}}
    depends_on:
      - db
      - redis

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB={{project_name}}
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
''',
            },
            dependencies=["docker", "docker-compose"],
        ),
    }
    
    def __init__(self, output_path: Path) -> None:
        """Initialize generator.
        
        Args:
            output_path: Where to generate the project
        """
        self.output_path = output_path
    
    def generate(
        self,
        template: ProjectTemplate,
        project_name: str,
        options: dict[str, Any] | None = None,
    ) -> list[Path]:
        """Generate project from template.
        
        Args:
            template: Template to use
            project_name: Name of the project
            options: Additional options
            
        Returns:
            List of created files
        """
        logger.info(
            "generating_project",
            template=template.value,
            project=project_name,
        )
        
        config = self.TEMPLATES.get(template)
        if not config:
            raise ValueError(f"Unknown template: {template}")
        
        created_files: list[Path] = []
        
        # Create project directory
        project_path = self.output_path / project_name
        project_path.mkdir(parents=True, exist_ok=True)
        
        # Generate files from template
        for file_path, content_template in config.files.items():
            # Replace placeholders
            content = content_template.replace("{{project_name}}", project_name)
            
            # Create file
            full_path = project_path / file_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content)
            created_files.append(full_path)
        
        # Create noode.yaml
        noode_config = self._generate_noode_config(project_name, config)
        config_path = project_path / "noode.yaml"
        config_path.write_text(noode_config)
        created_files.append(config_path)
        
        # Create V-Model structure
        self._create_vmodel_structure(project_path)
        
        logger.info(
            "project_generated",
            files=len(created_files),
            path=str(project_path),
        )
        
        return created_files
    
    def _generate_noode_config(
        self,
        project_name: str,
        config: TemplateConfig,
    ) -> str:
        """Generate noode.yaml configuration."""
        agents_config = "\n".join(
            f"  {agent}:\n    enabled: true"
            for agent in config.agents
        )
        
        return f"""# Noode Project Configuration
project:
  name: {project_name}
  template: {config.name}
  description: {config.description}
  version: 0.1.0

stack:
{chr(10).join(f'  - {s}' for s in config.stack)}

agents:
{agents_config}

security:
  veto_enabled: true
  auto_scan: true

knowledge:
  storage: local
  embedding_model: text-embedding-3-small
"""
    
    def _create_vmodel_structure(self, path: Path) -> None:
        """Create V-Model XT directory structure."""
        directories = [
            "00_Projektmanagement",
            "01_Anforderungen",
            "02_Systemarchitektur",
            "04_Test",
            "05_Qualitätssicherung",
            "06_Lieferung",
            ".noode/agents",
            ".noode/knowledge",
        ]
        
        for dir_name in directories:
            (path / dir_name).mkdir(parents=True, exist_ok=True)
    
    @classmethod
    def list_templates(cls) -> list[dict[str, str]]:
        """List available templates.
        
        Returns:
            List of template info dicts
        """
        return [
            {
                "id": template.value,
                "name": config.name,
                "description": config.description,
                "stack": ", ".join(config.stack),
            }
            for template, config in cls.TEMPLATES.items()
        ]
